# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rosetta < Formula
  desc ""
  homepage "https://github.com/oasdiff/rosetta-cli"
  version "0.0.7"

  on_macos do
    url "https://github.com/oasdiff/rosetta-cli/releases/download/v0.0.7/rosetta-cli_0.0.7_darwin_all.tar.gz"
    sha256 "17b612f0135eecf623b0d2963ea795cf38b1566d97db15761cccd03f4afad2a0"

    def install
      bin.install "rosetta-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasdiff/rosetta-cli/releases/download/v0.0.7/rosetta-cli_0.0.7_linux_arm64.tar.gz"
      sha256 "c31ca30ae6dfbf88025f742034b3d3e0f95a860439380ca7b92b76e584bb3131"

      def install
        bin.install "rosetta-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oasdiff/rosetta-cli/releases/download/v0.0.7/rosetta-cli_0.0.7_linux_amd64.tar.gz"
      sha256 "c7801eaf0c28e1fba3898aa976cc3effc0b30965ba61dfb7bda875de841c8961"

      def install
        bin.install "rosetta-cli"
      end
    end
  end
end
