# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rosetta < Formula
  desc ""
  homepage "https://github.com/oasdiff/rosetta-cli"
  version "0.0.2"

  on_macos do
    url "https://github.com/oasdiff/rosetta-cli/releases/download/v0.0.2/rosetta-cli_0.0.2_darwin_all.tar.gz"
    sha256 "ab0e265d25088986e5419031e43ce04cef994475ea9371ce782370a0b3d982bf"

    def install
      bin.install "rosetta-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/oasdiff/rosetta-cli/releases/download/v0.0.2/rosetta-cli_0.0.2_linux_amd64.tar.gz"
      sha256 "9697c6b982a0a6ae8e27469fb1ac38d5416230b5e0241bc432affeaeaccde6cd"

      def install
        bin.install "rosetta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasdiff/rosetta-cli/releases/download/v0.0.2/rosetta-cli_0.0.2_linux_arm64.tar.gz"
      sha256 "78c348f940e5800f643a77ec8acfd0b393e9a5eaec41c86fb73af1ee6c5183d0"

      def install
        bin.install "rosetta"
      end
    end
  end
end
