# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rosetta < Formula
  desc ""
  homepage "https://github.com/oasdiff/rosetta-release"
  version "0.0.8"

  on_macos do
    url "https://github.com/oasdiff/rosetta-cli/releases/download/v0.0.8/rosetta-cli_0.0.8_darwin_all.tar.gz"
    sha256 "9f6817a45a247b463372d920622687e1a6d6b8ef298c5db97df954616278fd7e"

    def install
      bin.install "rosetta-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasdiff/rosetta-cli/releases/download/v0.0.8/rosetta-cli_0.0.8_linux_arm64.tar.gz"
      sha256 "1202dd37b6ae49ab2643daabfb1f34888c565474b37759143391a99ad2148dd0"

      def install
        bin.install "rosetta-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oasdiff/rosetta-cli/releases/download/v0.0.8/rosetta-cli_0.0.8_linux_amd64.tar.gz"
      sha256 "0ebcc9166dff1c4e312f604d400fd5af41483112eef980e98ecfe40ec0fb7e8f"

      def install
        bin.install "rosetta-cli"
      end
    end
  end
end
